/**
 * Rebuilds interview-bank/INDEX.md from the entries in interview-bank/<category>/*.md.
 *
 *   npm run bank:index
 *
 * An entry is a `### Q: ...` heading followed by a line containing `**Status:** open|closed`
 * (see interview-bank/README.md for the template).
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..', 'interview-bank');
if (!existsSync(ROOT)) {
	console.error('interview-bank/ not found');
	process.exit(1);
}

type Entry = { question: string; status: 'open' | 'closed' | 'unknown'; verdict: string };
type FileInfo = { path: string; title: string; entries: Entry[] };

const categories = readdirSync(ROOT)
	.filter((name) => statSync(join(ROOT, name)).isDirectory())
	.sort();

const byCategory = new Map<string, FileInfo[]>();
for (const category of categories) {
	const dir = join(ROOT, category);
	const files = readdirSync(dir).filter((f) => f.endsWith('.md')).sort();
	const infos: FileInfo[] = files.map((file) => {
		const full = join(dir, file);
		const text = readFileSync(full, 'utf8');
		const title = text.match(/^# (.+)$/m)?.[1] ?? file.replace(/\.md$/, '');
		const entries: Entry[] = [];
		const blocks = text.split(/^### Q: /m).slice(1);
		for (const block of blocks) {
			const question = block.split(/\r?\n/)[0].trim();
			const status = block.match(/\*\*Status:\*\*\s*(open|closed)/i)?.[1]?.toLowerCase();
			const verdict = block.match(/\*\*Verdict:\*\*\s*(Correct|Partial|Wrong)/i)?.[1] ?? '?';
			entries.push({
				question,
				status: status === 'open' || status === 'closed' ? status : 'unknown',
				verdict
			});
		}
		return { path: relative(ROOT, full).replace(/\\/g, '/'), title, entries };
	});
	if (infos.length) byCategory.set(category, infos);
}

const all = [...byCategory.values()].flat().flatMap((f) => f.entries);
const open = all.filter((e) => e.status !== 'closed').length;
const closed = all.filter((e) => e.status === 'closed').length;

const out: string[] = [];
out.push('# Interview bank index');
out.push('');
out.push('> Generated by `npm run bank:index`. Do not edit by hand.');
out.push('');
out.push(`**${all.length} questions** · ${open} open · ${closed} closed · ${[...byCategory.values()].flat().length} files`);
out.push('');
out.push('## By category');
out.push('');
out.push('| Category | File | Questions | Open |');
out.push('| --- | --- | ---: | ---: |');
for (const [category, files] of byCategory) {
	for (const f of files) {
		const o = f.entries.filter((e) => e.status !== 'closed').length;
		out.push(`| ${category} | [${f.title}](${f.path}) | ${f.entries.length} | ${o ? `**${o}**` : '0'} |`);
	}
}
out.push('');
out.push('## Revise first (open gaps)');
out.push('');
let any = false;
for (const [category, files] of byCategory) {
	const rows = files.flatMap((f) =>
		f.entries.filter((e) => e.status !== 'closed').map((e) => `- [${e.question}](${f.path}) — ${e.verdict}`)
	);
	if (!rows.length) continue;
	any = true;
	out.push(`### ${category}`);
	out.push('');
	out.push(...rows);
	out.push('');
}
if (!any) out.push('Nothing open. 🎉', '');

writeFileSync(join(ROOT, 'INDEX.md'), out.join('\n'), 'utf8');
console.log(`INDEX.md written: ${all.length} questions, ${open} open.`);
